### ISSUE TITLE
Options Selection Control

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#1]
The Options control on  http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/ProductList.aspx?PrimaryShop=7&BasketID=102&sys_Tbl0Page=0&sys_Tbl0Sort=2 needs to be restyled.

![image](https://cloud.githubusercontent.com/assets/551874/9463674/3aefcac2-4b16-11e5-8fb6-5543229d381d.png)

Bahrul

Is this a better way to log and track issues, seems better than the way Freelancer handles emails?

**Comment by bahrul221** [comment]
please check the updates and this demo page http://demo.mbkom.com/08/netvide/options-control.html
