### ISSUE TITLE
Options checkboxes overwrite their labels

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#10]
http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/PriceCompare.aspx?PrimaryOnly=1&Order=AvgPrice,Product&ManufacturerID=500

IE 11, Win 7, Screen Res 1366x768, IE zoom 100%

Price Compare - pricecompare.aspx, the options checkboxes overwrite their labels

![image](https://cloud.githubusercontent.com/assets/551874/9607561/bdaf1278-50c1-11e5-8cbf-0f3347538492.png)

FogBugz 2581

**Comment by bahrul221** [comment]
please check here: http://demo.mbkom.com/08/netvide/form-inline.html
