### ISSUE TITLE
Highlighting Sortable Column Headers

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#11]
http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/DataObject.aspx?DataObject=CatMasterLinkDO

IE 11, Win 7, Screen Res 1366x768, IE zoom 100%

Until you hover the mouse on a column header there is no visual clue as to whether the column is sortable or not, whilst the mouse cursor does change to a hand and the text to red on hover, on a tablet there is no such clue.
Should there be more of a visual clue as to what is clickable?

![image](https://cloud.githubusercontent.com/assets/551874/9703576/7adacd94-5480-11e5-8b1c-eac6c416c382.png)

**Comment by bahrul221** [comment]
please check here: http://demo.mbkom.com/08/netvide/tables.html

**Comment by jconstan** [comment]
Changes are being implemented in our code
