### ISSUE TITLE
Problems with Right Alignment of Tables

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#12]
Tables right aligning themselves creates a lot of internal white space which make the data more difficult to read, see

http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/Manufacturer.aspx?ManufacturerID=490

as compared to 

http://netvide.weylite.co.uk:3210/BetaWeb/GroceryDev/Reports/Manufacturer.aspx?ManufacturerID=490

![image](https://cloud.githubusercontent.com/assets/551874/9703734/4def0a80-5484-11e5-881f-53b77480ecad.png)

**Comment by bahrul221** [comment]
please check here: http://demo.mbkom.com/08/netvide/tables.html

**Comment by bahrul221** [comment]
please update your style.css
