### ISSUE TITLE
Disabled links/buttons - remove red circle image on hover

### ISSUE THREAD

**Issue by Teletrak** [mbkom/project-netvide#14]
Hi Bahrul

Could you change the styling so that when the mouse is hovered over a link (or any button type) which has a class 'disabled' (or is disabled) it does not show the red circle (no entry) image. 

Thank you.
Jonathan

**Comment by bahrul221** [comment]
please update your style.css

check link-and-button.html file, or this page: http://demo.mbkom.com/08/netvide/link-and-button.html

**Comment by Teletrak** [comment]
New style.css didn't stop red circle on hover.
I had to use this hack to get the desired result:-
![disabled link - stop red circle](https://cloud.githubusercontent.com/assets/10403066/9846798/88e7d498-5acc-11e5-9ebd-31f61838027b.JPG)

**Comment by bahrul221** [comment]
could you give me url of the page that you implementing this?

**Comment by Teletrak** [comment]
On here http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/ProductList.aspx

**Comment by jconstan** [comment]
I don't see the problem on Chrome, Jonathan could you have a Caching problem

**Comment by bahrul221** [comment]
please update your style.css

**Comment by Teletrak** [comment]
Have implemented latest style.css, red circle has gone. Now have problem with button heights where font awesome icons used:-

![button heights 1](https://cloud.githubusercontent.com/assets/10403066/9851476/bf8e0822-5af0-11e5-8435-65dcc2566e88.JPG)

![button heights 2](https://cloud.githubusercontent.com/assets/10403066/9851485/ce9e2bbc-5af0-11e5-85c5-7e36e8531c15.JPG)

URLs
http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/ProductList.aspx
http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/Product.aspx?ProdID=464999

**Comment by bahrul221** [comment]
for the first one, please update style.css file

for the second one, you could add style to "PR" button : 
style="line-height: 1;"

**Comment by Teletrak** [comment]
Sorry to be a pain, but we don't want to style each button individually. We need a solution where we can mix font-awesome characters with ordinary characters and not have any differences in size, line height etc. (which is how it used to behave).

**Comment by bahrul221** [comment]
ok, I understand, no problem

**Comment by bahrul221** [comment]
please update your style.css file

**Comment by Teletrak** [comment]
I have just downloaded the project as a zip file, but it doesn't contain your latest changes.

**Comment by bahrul221** [comment]
sorry, my fault, please download again

**Comment by Teletrak** [comment]
No problem, got it now, thanks.
