### ISSUE TITLE
Paging controls underneath data tables - alignment & wrapping

### ISSUE THREAD

**Issue by Teletrak** [mbkom/project-netvide#15]
Hi Bahrul

We have opted to keep any data tables narrow by using width:auto (in small-table class) and in some cases setting explicit column widths as well.

We have adopted the following layout for the paging controls which sit underneath the tables:-

![paging](https://cloud.githubusercontent.com/assets/10403066/9767212/f7ffb6ea-5714-11e5-8d1e-1adb0548e6c5.JPG)

In the image above I have underlined two columns in blue and green.
Two things we need your help with:-

1. We want the paging controls to be the same width as the table i.e. the green column right aligning to the right edge of the data table.

2. If there is insufficient width, we want the green column to be aligned as closely to the blue column (but not to wrap underneath).

Hope that makes sense!
Regards
Jonathan

http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/MatchCentre.aspx

**Comment by bahrul221** [comment]
please update your style.css

please check tables.html file, or this demo page: http://demo.mbkom.com/08/netvide/tables.html at with pagination (fixed) section
