### ISSUE TITLE
Updated Style.css - Accessibility

### ISSUE THREAD

**Issue by Teletrak** [mbkom/project-netvide#16]
Hi Bahrul

Could you append/update your Style.css to reflect these css class changes:-
![style changes](https://cloud.githubusercontent.com/assets/10403066/9767326/95265bd6-5715-11e5-9fb9-f6f455617dcb.JPG)

But one problem I have caused is that the Accessibility large text feature no longer works because of the font-size specified in .pagination-wrap .pagination span.label classes - your help required!

http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/Site%20Accessibility.aspx

Regards
Jonathan

**Comment by bahrul221** [comment]
please update your style.css

**Comment by Teletrak** [comment]
New style.css doesn't include changes requested above.

**Comment by bahrul221** [comment]
I see, the font size of body is 12px, 
so please try replace :
.pagination-wrap .pagination span,label{
  font-size: 12px;
}

with this :
.pagination-sm>li>a, .pagination-sm>li>span{
    font-size: inherit;
}
