### ISSUE TITLE
Browser width

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#17]
As you can see from the image BOOTSTRAP seems to break the navigation bar 3 or 4cm before it needs to. The top half of the image shows the Browser a mm or two wider than the bottom half with the left and righthand components of the menu some 4 cm apart, butnarrowing the browser slightly causes the both navigation bars to be split

![image](https://cloud.githubusercontent.com/assets/551874/9777333/0360a2ba-575b-11e5-9988-063b75b8fb47.png)

**Comment by bahrul221** [comment]
please update your style.css

please check dashboard.html file at line 29 and 35 (header section)
