### ISSUE TITLE
Page Navigation

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#2]
![image](https://cloud.githubusercontent.com/assets/551874/9488453/1adbb3e2-4bd2-11e5-9b5b-7d6f290f5857.png)

Page Navigation control needs restyling it can be found on this page http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/ProductList.aspx?PrimaryShop=7&BasketID=102&sys_Tbl0Page=0&sys_Tbl0Sort=2

**Comment by bahrul221** [comment]
please check here: http://demo.mbkom.com/08/netvide/product-list.html
