### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#3]
Fix Accessibility (http://netvide.weylite.co.uk:3210/BetaUIWeb/Reports/Site%20Accessibility.aspx), currently this injects a small css to change key defaults when different Text modes are supported.

**Comment by bahrul221** [comment]
please update your style.css

**Comment by jconstan** [comment]
Large Text Mode uses smaller font than the Default mode (see below), Perhaps we should look at this after we've finalized the default font size and use of white space.

![image](https://cloud.githubusercontent.com/assets/551874/9610164/c5299966-50cf-11e5-8c7a-5e5d518dbbe4.png)

**Comment by bahrul221** [comment]
I will update for this, tomorrow, thank you

**Comment by bahrul221** [comment]
please update you style.css
