### ISSUE TITLE
Restyle Comments Form

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#4]
Click here 
![image](https://cloud.githubusercontent.com/assets/551874/9488504/6718891a-4bd2-11e5-946b-0fcbe07bd10f.png)

or load http://netvide.weylite.co.uk:3210/BetaUIWeb/Reports/formmail.aspx?to=Vikki_Dunning@NETVide.com&subject=Comment+on+Grocery+Development+Price+Monitor%27%0a&body=%0a%0a%0aComment+on+Grocery+Development+Price+Monitor%27%0ahttp%3a%2f%2fnetvide.weylite.co.uk%3a3210%2fBetaUIWeb%2fReports%2fdefault.aspx&AutoClose=true#

**Comment by bahrul221** [comment]
please check here: http://demo.mbkom.com/08/netvide/comment-form.html
