### ISSUE TITLE
ReStyle Help Pages

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#5]
Just restyle the Table of Comments and one of the Detail pages we can then implement the changes accross the rest of the Help system

Help Pages (http://netvide.weylite.co.uk:3210/BetaUIWeb/Reports/Help.aspx)

**Comment by bahrul221** [comment]
please check here: http://demo.mbkom.com/08/netvide/help.html 
and here: http://demo.mbkom.com/08/netvide/help-dashboard.html
