### ISSUE TITLE
Restyle Brand Detail Page

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#6]
![image](https://cloud.githubusercontent.com/assets/551874/9488575/f0997500-4bd2-11e5-9f58-b06e7e36364f.png)

Brand Detail Page (http://netvide.weylite.co.uk:3210/BetaUIWeb/Reports/Manufacturer.aspx?ManufacturerID=2250)

**Comment by bahrul221** [comment]
please check here: http://demo.mbkom.com/08/netvide/brand-detail.html
