### ISSUE TITLE
Restyle Product Detail Page

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#7]
![image](https://cloud.githubusercontent.com/assets/551874/9488640/41beb0d0-4bd3-11e5-9406-f83b502c6597.png)

Product Detail Page (http://netvide.weylite.co.uk:3210/BetaUIWeb/Reports/Product.aspx?ProdID=346315)

**Comment by bahrul221** [comment]
please check here: http://demo.mbkom.com/08/netvide/product-detail.html
