### ISSUE TITLE
Menu with SubMenu's

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#8]
We have another product which uses  the same code base, but it also 

uses sub menus like this
![image](https://cloud.githubusercontent.com/assets/551874/9489517/89ad652a-4bd9-11e5-98b0-dc14a1da90de.png)

Could you update the example code in TaskManager Login.zip which I'll send separately so that the menu and submenu are correctly displayed

**Comment by bahrul221** [comment]
please check here: http://demo.mbkom.com/08/netvide/navbar.html

**Comment by jconstan** [comment]
This is the code that we generate, which includes the site-navbar-hover
![image](https://cloud.githubusercontent.com/assets/551874/9542343/ccfa2e0a-4d67-11e5-91c9-6700c45caaa1.png)

However if you check the source after loading the page in Chrome that element has been removed
![image](https://cloud.githubusercontent.com/assets/551874/9542377/15423a04-4d68-11e5-8261-e12a5cb9d490.png)

**Comment by bahrul221** [comment]
are you sure this code for the page
![15423a04-4d68-11e5-8261-e12a5cb9d490_](https://cloud.githubusercontent.com/assets/10630875/9542572/79ee2ed6-4da4-11e5-8ab0-67491931ac52.png)
![ccfa2e0a-4d67-11e5-91c9-6700c45caaa1_](https://cloud.githubusercontent.com/assets/10630875/9542571/79a965e4-4da4-11e5-9d52-b1ee3b566506.png)
