### ISSUE TITLE
Font size & White Space

### ISSUE THREAD

**Issue by jconstan** [mbkom/project-netvide#9]
Ours is a data heavy site and the current font size and use of white space means that only half the data is visible by default and that even a fairly narrow table fills the whole width of the screen, Can you make some styling changes to try and recover the space available while keeping the clean designh you've achieved. As you can see from the attached screen shots on the same resolution the current design displays all 20 products plus the navigation controls without the need to use the scroll bars

![image](https://cloud.githubusercontent.com/assets/551874/9545236/5cf6c3c6-4d7f-11e5-8f8e-1012971fdb4f.png)

![image](https://cloud.githubusercontent.com/assets/551874/9545260/b4c80682-4d7f-11e5-90cf-504f5272e56d.png)

**Comment by bahrul221** [comment]
please review the demo page before I upload it on github? http://demo.mbkom.com/08/netvide/

**Comment by jconstan** [comment]
Bahrul

 

Sorry I didn’t get back to you yesterday but we had a national holiday, I’ve looked at the new demo and I think we still need to recover some vertical space, as you can see by the side by side images below the headers are now the same size but the design is very generous with white space around the H1 title, so the table starts much further down the page than it does currently.

 

John

**Comment by jconstan** [comment]
Related Issue

http://netvide.weylite.co.uk:3210/BetaUIWeb/GroceryDev/Reports/mastercategoryrange.aspx

IE11, Win7, Full screen mode, 100% zoom, resolution 1366 x 768

Range Analysis By Master Category -  mastercategoryrange.aspx

Range Tab -> Analyze a shop's product range either using NETvide's Master Categories

Range Analysis table now wider than screen.
Old UI whole table could be seen.


![image](https://cloud.githubusercontent.com/assets/551874/9703479/25fd4818-547d-11e5-94b5-a6af236de7fb.png)

**Comment by bahrul221** [comment]
please check demo page again

**Comment by jconstan** [comment]
Page density is much closer to the original design, default font size is 12px however this does mean that the page and export controls are a little large, can you look at reducing their size in keeping with the rest of the page, Plus any other suggestions/ideas you have for a more compact page.

![capture](https://cloud.githubusercontent.com/assets/551874/9741609/30b1793c-5653-11e5-968e-f0861490ae00.PNG)

**Comment by bahrul221** [comment]
just add btn-sm to export link

**Comment by Teletrak** [comment]
I have actually used btn-xs to be consistent with other button sizes.

**Comment by bahrul221** [comment]
the difference between btn-xs and btn-sm is the padding, I think btn-xs is too small, but it's up to you
